# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838896005ec23f381225fe7666001c25a58c106919069b6b7bb3ff13f7516ee82c5c104d7a4d831648be4cbec44b2b03aa8b8a0a6bdb54ff8552183a948e8210

test:
  secret_key_base: de7ebfcfe65e6751261da65c766c861a703ce7a288c7f911ba71a155b8fa181bbf2047ecf28e06d995ce39fcd3b997fef717f05c0cd4507a2525a118d6d38744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
